name: family_financial_assistant
description: Мобильное приложение "Семейный Финансовый Ассистент" (Offline-First)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.12.0'

dependencies:
  flutter:
    sdk: flutter
  workmanager: ^0.9.0+3
  logger: ^2.0.0

  # State Management
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3       

  # Database (Offline-First)
  drift: ^2.34.0
  drift_flutter: ^0.3.0  
  sqlite3: ^3.3.3
  path_provider: ^2.1.5
  
  # Backend & Sync
  supabase_flutter: ^2.15.0
  uuid: ^4.5.3    
  
  # Фоновые задачи
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.1 
  
  # Routing
  go_router: ^17.3.0                 
  
  # Security & Encryption
  flutter_secure_storage: ^10.3.1
  pointycastle: ^4.0.0
  
  # OCR (Скриншоты кэшбэка)
  google_mlkit_text_recognition: ^0.15.1
  
  # Notifications
  flutter_local_notifications: ^22.0.1
  
  # Export & Time
  excel: ^4.0.6
  timezone: ^0.11.0                  
  
  # Device Info
  device_info_plus: ^13.1.0         
  package_info_plus: ^10.1.0        

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0             
  
  # Code Generators
  build_runner: ^2.15.0             
  freezed: ^3.2.5                    
  json_serializable: ^6.14.0         
  drift_dev: ^2.34.0
  riverpod_generator: ^4.0.4

flutter:
  uses-material-design: true

  # others
  # _fe_analyzer_shared: ^104.0.0
  # analyzer: ^14.0.0
  # archive: ^4.0.9
  # cli_util: ^0.5.1
  # dart_style: ^3.1.9
  # flutter_secure_storage_darwin: ^0.4.0
  # freezed: ^4.0.0-dev.3
  # matcher: ^0.12.20
  # meta: ^1.18.3
  # mockito: ^5.7.0
  # package_config: ^3.0.0
  # test: ^1.31.1
  # test_api: ^0.7.12
  # test_core: ^0.6.18
  # vector_math: ^2.4.0
  # xml: ^7.0.1